### ISSUE TITLE
gfortran-9 parentheses issue on MacOSX

### ISSUE THREAD

**Issue by badw** [jbuckeridge/cplap#1]
when running `make` I get the issue: 

```
 2546 |                    &eqns(i,nspecies_dep+1)/eqns(i,2) + -eqns(1,nspecies_dep+1)/eqns(1,1)&
      |                                                        1
Warning: Extension: Unary operator following arithmetic operator (use parentheses) at (1)
```

when running with `gfortran-9` on MacOSX 
adding parentheses to `line 2546` to:
```
&eqns(i,nspecies_dep+1)/eqns(i,2) +(-eqns(1,nspecies_dep+1)/eqns(1,1))&
```
seems to solve this problem (but thought I would double check I have put them in the right place as I am not a fortran guru in any sense)

**Comment by jbuckeridge** [comment]
It's just a warning though isn't it? That's what I get when I compile with gfortran, so it still works fine. You shouldn't need to change the source code, the compiler should do it itself. However, the change you made is correct.

**Comment by badw** [comment]
ha! yep you are right! In my haste I neglected to see whether it had actually compiled! 
sorry about that!
